### ISSUE TITLE
关于 Set-Cookie 更新问题

### ISSUE THREAD

**Issue by fwqaaq** [wobisheng/esp8266_authentication#1]
https://github.com/wobisheng/ntu_esp8266_authentication/blob/3d955465946643ff46af1e0a55aed0093c9ac2bc/wifi_authentication.ino#L31

如果 cookie 已经种下了，是不是不会有 set-cookie 字段，还有关于如（承载 openwrt 等硬件设备）上的轮询时间是什么样的

**Comment by wobisheng** [comment]
是这样的，这句话的目的是提取第一次请求中的set-cookie信息，然后放到第二次请求的cookie里面，相当于我第一次请求到的set-cookie放到第二次
我刚刚尝试了一下，如果提前将PHPSESSID(Cookie)设置好然后进行请求也是可以做到相同的效果，并且只需要请求一次，是个好办法。
openwrt的轮询时间设置可以是半个小时检查一次，因为具体多久会自动掉线我也不是很清楚。但是只要这个设备一直存在网络请求，那他就不会掉线。

**Comment by fwqaaq** [comment]
因为之前尝试一段时间它就会过期，并且你写的获取 set-cookie 和发出获取流量的请求是一个 url？

**Comment by wobisheng** [comment]
对，不带cookie请求时，这个认证url会返回给你一个set-cookie。我觉得是不是因为长时间没有网络连接导致的过期掉线

**Comment by wobisheng** [comment]
不过现在发现好像不加cookie其实也可以直接认证，就是一条get请求的事情
```
import requests
import socket
Ip = socket.gethostbyname(socket.gethostname())
username = ""
password = ""
URL = "http://210.29.79.141:801/eportal/?c=Portal&a=login&callback=dr1003&login_method=1&user_account=,0,"+username+"&user_password="+password+"&wlan_user_ip="+Ip+"&wlan_user_ipv6=&wlan_user_mac=000000000000&wlan_ac_ip=&wlan_ac_name=&jsVersion=3.3.2&v=7328"
r = requests.get(URL)
print(r)
```

**Comment by fwqaaq** [comment]
我试了一下，确实是可以的😄

**Comment by fwqaaq** [comment]
可以试试苹果的 快捷指令 🤔

**Comment by fwqaaq** [comment]
* 好思路🐮，如果不用 cookie，那很完美
https://www.icloud.com/shortcuts/9d9cad4b42004fd7abe2acd6b998dcbd

**Comment by fwqaaq** [comment]
还遇到一个代理的问题，尽管隔离这个域名，但是还是会不成功🤔

**Comment by wobisheng** [comment]
嘶，我试了一下我这个没问题呀，是不是哪个地方格式写的有问题，你可以试试把801端口也加进去

**Comment by fwqaaq** [comment]
> 嘶，我试了一下我这个没问题呀，是不是哪个地方格式写的有问题，你可以试试把801端口也加进去

😂，没想到这么简单，之前大意了

**Comment by wobisheng** [comment]
哈哈哈哈哈
